### ISSUE TITLE
Documentation - How to work with code generators

### ISSUE THREAD

**Issue by masoudtahmasebi93** [bit-foundation/bit-framework#121]
Hi, I've created all of my model and relations and I'm struggling to work with the generators, is there any documentation on how to work with the generators?

I want to generate controllers and views for my models

I've checked the document and unfortunately didn't find the information about this topic. I've tried to run bittools and add the code generation project to the main project.

**Comment by ysmoradi** [comment]
Hi. Clone and build a [sample app](https://github.com/ysmoradi/BitSampleApp). Our code generator, **generates odata enabled client-side proxy** you need to call server side. So when you write following:

```csharp
[Function]
public virtual async Task<IQueryable<CategoryDto>> GetEmptyCategories(CancellationToken cancellationToken)
{
	return ...
}
```
We generate a context, which contains categories and GetEmptyCategories method. If you call that method at client side, we call its equivalent server side method.
```typescript
context.categories.getEmptyCategories();
```
You've access to odata features such as $batch, $filter, $orderBy, $skip etc. For example:
```typescript
context.categories.getEmptyCategories().take(10);
```

**Comment by pesarkuchulu** [comment]
Thank you for your quick response,
I've made changes so that the sample app now is using sql server and the angular is using Core-Ui and the code generation is working perfectly for creating TS models from the Dto models, right now I have a problem about how this whole combination could be published.

I've published both projects (Sample C# app publish using VS and Angular using ng build --prod) unfortunately both side has little problems  :
Backend problem:
 `An error occurred while starting the application.
JsonReaderException: After parsing a value an unexpected character was encountered: ". Path '[0].Configs[1].Value', line 17, position 117.
Newtonsoft.Json.JsonTextReader.ParsePostValue(bool ignoreComments)

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor)

DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Object (DelegateActivator), Services = [Bit.Core.Models.AppEnvironment], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Exception has been thrown by the target of an invocation. (See inner exception for details.)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)

DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IAspNetCoreMiddlewareConfiguration[] (DelegateActivator), Services = [System.Collections.Generic.IEnumerable`1[[Bit.OwinCore.Contracts.IAspNetCoreMiddlewareConfiguration, Bit.OwinCore, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Object (DelegateActivator), Services = [Bit.Core.Models.AppEnvironment], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Exception has been thrown by the target of an invocation. (See inner exception for details.) (See inner exception for details.)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)

Exception: Could not resolve a service of type 'System.Collections.Generic.IEnumerable`1[[Bit.OwinCore.Contracts.IAspNetCoreMiddlewareConfiguration, Bit.OwinCore, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null]]' for the parameter 'aspNetCoreMiddlewares' of method 'Configure' on type 'Bit.OwinCore.AspNetCoreAppStartup'.
Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)

JsonReaderException: After parsing a value an unexpected character was encountered: ". Path '[0].Configs[1].Value', line 17, position 117.
Newtonsoft.Json.JsonTextReader.ParsePostValue(bool ignoreComments)
Newtonsoft.Json.JsonTextReader.Read()
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, string id)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, string id)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, object existingValue, string id)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, object target)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, string id)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, string id)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, object existingValue, string id)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, bool checkAdditionalContent)
Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
Newtonsoft.Json.JsonConvert.DeserializeObject(string value, Type type, JsonSerializerSettings settings)
Newtonsoft.Json.JsonConvert.DeserializeObject<T>(string value, JsonSerializerSettings settings)
Bit.Core.Implementations.DefaultJsonContentFormatter.DeSerialize<T>(string objAsStr) in DefaultJsonContentFormatter.cs
Bit.Core.Implementations.DefaultAppEnvironmentsProvider.GetActiveAppEnvironment() in DefaultAppEnvironmentsProvider.cs
Bit.Core.Contracts.IDependencyManagerExtensions+<>c.<RegisterMinimalDependencies>g__RegisterAppEnvironment|2_0(IDependencyResolver resolver) in IDependencyManagerExtensions.cs
Bit.Owin.Implementations.AutofacDependencyManager+<>c__DisplayClass29_0<T>.<RegisterUsing>b__0(IDependencyResolver depManager) in AutofacDependencyManager.cs

Show raw exception details
TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor)
System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(object obj, object[] parameters, object[] arguments)
System.Delegate.DynamicInvokeImpl(object[] args)
Bit.Owin.Implementations.AutofacDependencyManager+<>c__DisplayClass31_0.<RegisterUsing>b__0(IComponentContext context, IEnumerable<Parameter> parameter) in AutofacDependencyManager.cs
Autofac.Builder.RegistrationBuilder+<>c__DisplayClass0_0<T>.<ForDelegate>b__0(IComponentContext c, IEnumerable<Parameter> p)
Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)

Show raw exception details
DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Object (DelegateActivator), Services = [Bit.Core.Models.AppEnvironment], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Exception has been thrown by the target of an invocation. (See inner exception for details.)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func<object> creator)
Autofac.Core.Resolving.InstanceLookup.Execute()
Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable<Parameter> parameters)
Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable<Parameter> parameters, out object instance)
Autofac.Core.Activators.Reflection.AutowiringPropertyInjector.InjectProperties(IComponentContext context, object instance, IPropertySelector propertySelector, IEnumerable<Parameter> parameters)
Autofac.Builder.RegistrationBuilder<TLimit, TActivatorData, TRegistrationStyle>+<>c__DisplayClass32_0.<PropertiesAutowired>b__1(object s, ActivatingEventArgs<object> e)
Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable<Parameter> parameters, ref object instance)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func<object> creator)
Autofac.Core.Resolving.InstanceLookup.Execute()
Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable<Parameter> parameters)
Autofac.Features.Collections.CollectionRegistrationSource+<>c__DisplayClass0_1.<RegistrationsFor>b__2(IComponentRegistration cr)
System.Linq.Enumerable+WhereSelectEnumerableIterator<TSource, TResult>.MoveNext()
System.Linq.Buffer<TElement>..ctor(IEnumerable<TElement> source)
System.Linq.Enumerable.ToArray<TSource>(IEnumerable<TSource> source)
Autofac.Features.Collections.CollectionRegistrationSource+<>c__DisplayClass0_0.<RegistrationsFor>b__0(IComponentContext c, IEnumerable<Parameter> p)
Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)

Show raw exception details
DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IAspNetCoreMiddlewareConfiguration[] (DelegateActivator), Services = [System.Collections.Generic.IEnumerable`1[[Bit.OwinCore.Contracts.IAspNetCoreMiddlewareConfiguration, Bit.OwinCore, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Object (DelegateActivator), Services = [Bit.Core.Models.AppEnvironment], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Exception has been thrown by the target of an invocation. (See inner exception for details.) (See inner exception for details.)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.Execute()
Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable<Parameter> parameters)
Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable<Parameter> parameters)
Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable<Parameter> parameters, out object instance)
Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable<Parameter> parameters)
Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)

Show raw exception details
Exception: Could not resolve a service of type 'System.Collections.Generic.IEnumerable`1[[Bit.OwinCore.Contracts.IAspNetCoreMiddlewareConfiguration, Bit.OwinCore, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null]]' for the parameter 'aspNetCoreMiddlewares' of method 'Configure' on type 'Bit.OwinCore.AspNetCoreAppStartup'.
Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder+<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter+<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()`

FrontEnd:
`ClientAppProfile:1 Failed to load resource: the server responded with a status of 404 (Not Found)
scripts.44f911901dd212b039b7.js:1 Uncaught ReferenceError: clientAppProfile is not defined
    at e.init (scripts.44f911901dd212b039b7.js:1)
    at Bit (scripts.44f911901dd212b039b7.js:1)
    at scripts.44f911901dd212b039b7.js:1
main.54ab6df42dad5379d31c.js:1 Uncaught TypeError: Cannot read property 'DefaultSecurityService' of undefined
    at Object.zUnb (main.54ab6df42dad5379d31c.js:1)
    at c (runtime.7e148c8fb5ba3477c740.js:1)
    at Object.7 (main.54ab6df42dad5379d31c.js:1)
    at c (runtime.7e148c8fb5ba3477c740.js:1)
    at t (runtime.7e148c8fb5ba3477c740.js:1)
    at Array.r [as push] (runtime.7e148c8fb5ba3477c740.js:1)
    at main.54ab6df42dad5379d31c.js:1`

**Comment by pesarkuchulu** [comment]
Additional Information about deployment platform:
Windows Server 2012 R2 , IIS 8.5

**Comment by pesarkuchulu** [comment]
I bypassed proxy by linking this line in index.html :
<script src="ClientAppProfile" type="text/javascript"></script>
to the main server , like:
<script src="http://serverDomain:17563/ClientAppProfile" type="text/javascript"></script>

and I defined a baseURL variable in bit.core for requests, which resolved the issue for now.

**Comment by ysmoradi** [comment]
I'm gonna publish that sample app to make sure it has tuned configuration.

**Comment by pesarkuchulu** [comment]
Thank you 👍

**Comment by ysmoradi** [comment]
Check this out!
https://github.com/bit-foundation/ToDoLine
