### ISSUE TITLE
Hijri calendar does not show correctly when bit calendar dynamically added to the view

### ISSUE THREAD

**Issue by Poorsam2** [bit-foundation/bit-framework#179]
var datePicker = new BitDateTimePicker
                             {
                                 Culture = new CultureInfo("Fa"),
                                 Text = "لطفا تاریخ مورد تایید را انتخاب نمایید",
                                 DateTimeDisplayFormat = "dd MMM yyyy",
                                 CalendarSystem = CalendarSystem.PersianArithmetic,
                                 FlowDirection = FlowDirection.RightToLeft,
                            

                             };
                             datePicker.SetBinding(BitDateTimePicker.SelectedDateTimeProperty, pr);
pr is a date time property

![bug](https://user-images.githubusercontent.com/59330124/71554235-f3301480-2a31-11ea-887c-f3ee28df30e3.png)

**Comment by ysmoradi** [comment]
Could you please provide me a simple repo?

**Comment by Poorsam2** [comment]
sure:
https://github.com/Poorsam2/Saman.git

**Comment by ysmoradi** [comment]
There is a Xaml specific thing in BitDateTimePicker called TypeConverter on a Culture property. When you set Culture="Fa" in xaml, it uses that type converter to convert string to culture info.
It uses a class called CultureInfoProvider in background which fixes Persian and Arabic culture issues.
To use BitDatePicker in csharp, use following code:

```cs
Culture = CultureInfoProvider.Current.GetCultureInfo("Fa"),
```
instead of
```cs
Culture = new CultureInfo("fa"),
```

**Comment by Poorsam2** [comment]
thanks dude it was solved
